/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables.records


import com.spotteacher.infra.db.tables.LessonScheduleReports

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class LessonScheduleReportsRecord private constructor() : UpdatableRecordImpl<LessonScheduleReportsRecord>(LessonScheduleReports.LESSON_SCHEDULE_REPORTS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var lessonScheduleId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open var name: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var fourStepRating: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var comment: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var yesOrNo: Boolean?
        set(value): Unit = set(5, value)
        get(): Boolean? = get(5) as Boolean?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised LessonScheduleReportsRecord
     */
    constructor(id: Long? = null, lessonScheduleId: Long, name: String, fourStepRating: Int? = null, comment: String? = null, yesOrNo: Boolean? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null): this() {
        this.id = id
        this.lessonScheduleId = lessonScheduleId
        this.name = name
        this.fourStepRating = fourStepRating
        this.comment = comment
        this.yesOrNo = yesOrNo
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
