/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables.records


import com.spotteacher.infra.db.tables.LessonReservationEducations

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class LessonReservationEducationsRecord private constructor() : UpdatableRecordImpl<LessonReservationEducationsRecord>(LessonReservationEducations.LESSON_RESERVATION_EDUCATIONS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var lessonReservationId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open var educationId: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    open var createdAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised LessonReservationEducationsRecord
     */
    constructor(id: Long? = null, lessonReservationId: Long, educationId: Long, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null): this() {
        this.id = id
        this.lessonReservationId = lessonReservationId
        this.educationId = educationId
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
