/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables.records


import com.spotteacher.infra.db.tables.LessonReservationDates

import java.time.LocalDate
import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * 授業予約の日付
 */
@Suppress("warnings")
open class LessonReservationDatesRecord private constructor() : UpdatableRecordImpl<LessonReservationDatesRecord>(LessonReservationDates.LESSON_RESERVATION_DATES) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var lessonReservationId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open var startDate: LocalDate
        set(value): Unit = set(2, value)
        get(): LocalDate = get(2) as LocalDate

    open var startTime: LocalDateTime
        set(value): Unit = set(3, value)
        get(): LocalDateTime = get(3) as LocalDateTime

    open var endTime: LocalDateTime
        set(value): Unit = set(4, value)
        get(): LocalDateTime = get(4) as LocalDateTime

    open var createdAt: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised LessonReservationDatesRecord
     */
    constructor(id: Long? = null, lessonReservationId: Long, startDate: LocalDate, startTime: LocalDateTime, endTime: LocalDateTime, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null): this() {
        this.id = id
        this.lessonReservationId = lessonReservationId
        this.startDate = startDate
        this.startTime = startTime
        this.endTime = endTime
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
