/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables.records


import com.spotteacher.infra.db.tables.LessonScheduleSubjects

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class LessonScheduleSubjectsRecord private constructor() : UpdatableRecordImpl<LessonScheduleSubjectsRecord>(LessonScheduleSubjects.LESSON_SCHEDULE_SUBJECTS) {

    open var lessonScheduleId: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    open var subjectCode: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var displayOrder: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Long?, String?> = super.key() as Record2<Long?, String?>

    /**
     * Create a detached, initialised LessonScheduleSubjectsRecord
     */
    constructor(lessonScheduleId: Long, subjectCode: String, displayOrder: Int? = null): this() {
        this.lessonScheduleId = lessonScheduleId
        this.subjectCode = subjectCode
        this.displayOrder = displayOrder
        resetTouchedOnNotNull()
    }
}
