services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./local-db/mysql:/var/lib/mysql
      - ./local-db/init/init.sql:/docker-entrypoint-initdb.d/init.sql  # 初期データSQLのマウント
    networks:
      - local-spot-teacher-network
#  minio: #S3のローカル用
#    image: minio/minio:latest
#    container_name: minio
#    ports:
#      - "9010:9010"
#      - "9011:9011"
#    environment:
#      MINIO_ROOT_USER: minio
#      MINIO_ROOT_PASSWORD: password
#      # secret key の準備
#      MINIO_KMS_SECRET_KEY: minio-key
#    entrypoint: |
#      /bin/sh -c "
#      mkdir -p /root/.minio && \
#      echo '{
#        \"version\": \"1\",
#        \"kms\": {
#          \"secret\": {
#            \"keys\": {
#              \"minio-key\": {
#                \"key\": \"\"
#              }
#            }
#          }
#        }
#      }' > /root/.minio/config.json && \
#      exec minio server /data --address :9010 --console-address :9011
#      "
#    volumes:
#      - ./local-db/minio:/data
networks:
  local-spot-teacher-network:
    driver: bridge
volumes:
  minio_data:
