/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.10.0"
}

rootProject.name = "spot-teacher"
include(":db")
include(":admin")
include(":shared")
include(":testUtil")

//project(":db").projectDir = file("db")
//project(":admin").projectDir = file("admin")
//project(":shared").projectDir = file("shared")
//project(":testUtil").projectDir = file("testUtil")

dependencyResolutionManagement {
    versionCatalogs {
        create("libs")
    }
}
