/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables

import com.spotteacher.infra.db.tables.records.CompaniesRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime
import kotlin.collections.Collection

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Companies(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CompaniesRecord>?,
    parentPath: InverseForeignKey<out Record, CompaniesRecord>?,
    aliased: Table<CompaniesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<CompaniesRecord>(
    alias,
    null,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>companies</code>
         */
        val COMPANIES: Companies = Companies()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CompaniesRecord> = CompaniesRecord::class.java

    /**
     * The column <code>companies.id</code>.
     */
    val ID: TableField<CompaniesRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>companies.name</code>.
     */
    val NAME: TableField<CompaniesRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>companies.prefecture</code>.
     */
    val PREFECTURE: TableField<CompaniesRecord, String?> = createField(DSL.name("prefecture"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>companies.city</code>.
     */
    val CITY: TableField<CompaniesRecord, String?> = createField(DSL.name("city"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>companies.street</code>.
     */
    val STREET: TableField<CompaniesRecord, String?> = createField(DSL.name("street"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>companies.post_code</code>.
     */
    val POST_CODE: TableField<CompaniesRecord, String?> = createField(DSL.name("post_code"), SQLDataType.VARCHAR(7).nullable(false), this, "")

    /**
     * The column <code>companies.phone_number</code>.
     */
    val PHONE_NUMBER: TableField<CompaniesRecord, String?> = createField(DSL.name("phone_number"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>companies.url</code>.
     */
    val URL: TableField<CompaniesRecord, String?> = createField(DSL.name("url"), SQLDataType.VARCHAR(1000), this, "")

    /**
     * The column <code>companies.created_at</code>.
     */
    val CREATED_AT: TableField<CompaniesRecord, LocalDateTime?> = createField(
        DSL.name("created_at"),
        SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)),
        this,
        ""
    )

    /**
     * The column <code>companies.updated_at</code>.
     */
    val UPDATED_AT: TableField<CompaniesRecord, LocalDateTime?> = createField(
        DSL.name("updated_at"),
        SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)),
        this,
        ""
    )

    private constructor(alias: Name, aliased: Table<CompaniesRecord>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CompaniesRecord>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CompaniesRecord>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>companies</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>companies</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>companies</code> table reference
     */
    constructor() : this(DSL.name("companies"), null)
    override fun getIdentity(): Identity<CompaniesRecord, Long?> = super.getIdentity() as Identity<CompaniesRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<CompaniesRecord> = Internal.createUniqueKey(Companies.COMPANIES, DSL.name("KEY_companies_PRIMARY"), arrayOf(Companies.COMPANIES.ID), true)
    override fun `as`(alias: String): Companies = Companies(DSL.name(alias), this)
    override fun `as`(alias: Name): Companies = Companies(alias, this)
    override fun `as`(alias: Table<*>): Companies = Companies(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Companies = Companies(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Companies = Companies(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Companies = Companies(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Companies = Companies(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Companies = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Companies = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Companies = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Companies = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Companies = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Companies = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Companies = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Companies = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Companies = where(DSL.notExists(select))
}
