/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables


import com.spotteacher.infra.db.tables.records.LessonReservationDatesRecord

import java.time.LocalDate
import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * 授業予約の日付
 */
@Suppress("warnings")
open class LessonReservationDates(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, LessonReservationDatesRecord>?,
    parentPath: InverseForeignKey<out Record, LessonReservationDatesRecord>?,
    aliased: Table<LessonReservationDatesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<LessonReservationDatesRecord>(
    alias,
    null,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("授業予約の日付"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>lesson_reservation_dates</code>
         */
        val LESSON_RESERVATION_DATES: LessonReservationDates = LessonReservationDates()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<LessonReservationDatesRecord> = LessonReservationDatesRecord::class.java

    /**
     * The column <code>lesson_reservation_dates.id</code>.
     */
    val ID: TableField<LessonReservationDatesRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>lesson_reservation_dates.lesson_reservation_id</code>.
     */
    val LESSON_RESERVATION_ID: TableField<LessonReservationDatesRecord, Long?> = createField(DSL.name("lesson_reservation_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>lesson_reservation_dates.start_date</code>.
     */
    val START_DATE: TableField<LessonReservationDatesRecord, LocalDate?> = createField(DSL.name("start_date"), SQLDataType.LOCALDATE.nullable(false), this, "")

    /**
     * The column <code>lesson_reservation_dates.start_time</code>.
     */
    val START_TIME: TableField<LessonReservationDatesRecord, LocalDateTime?> = createField(DSL.name("start_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "")

    /**
     * The column <code>lesson_reservation_dates.end_time</code>.
     */
    val END_TIME: TableField<LessonReservationDatesRecord, LocalDateTime?> = createField(DSL.name("end_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "")

    /**
     * The column <code>lesson_reservation_dates.created_at</code>.
     */
    val CREATED_AT: TableField<LessonReservationDatesRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>lesson_reservation_dates.updated_at</code>.
     */
    val UPDATED_AT: TableField<LessonReservationDatesRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<LessonReservationDatesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<LessonReservationDatesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<LessonReservationDatesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>lesson_reservation_dates</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>lesson_reservation_dates</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>lesson_reservation_dates</code> table reference
     */
    constructor(): this(DSL.name("lesson_reservation_dates"), null)
    override fun getIdentity(): Identity<LessonReservationDatesRecord, Long?> = super.getIdentity() as Identity<LessonReservationDatesRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<LessonReservationDatesRecord> = Internal.createUniqueKey(LessonReservationDates.LESSON_RESERVATION_DATES, DSL.name("KEY_lesson_reservation_dates_PRIMARY"), arrayOf(LessonReservationDates.LESSON_RESERVATION_DATES.ID), true)
    override fun getUniqueKeys(): List<UniqueKey<LessonReservationDatesRecord>> = listOf(
        Internal.createUniqueKey(LessonReservationDates.LESSON_RESERVATION_DATES, DSL.name("KEY_lesson_reservation_dates_lesson_reservation_id"), arrayOf(LessonReservationDates.LESSON_RESERVATION_DATES.LESSON_RESERVATION_ID, LessonReservationDates.LESSON_RESERVATION_DATES.START_DATE), true)
    )
    override fun `as`(alias: String): LessonReservationDates = LessonReservationDates(DSL.name(alias), this)
    override fun `as`(alias: Name): LessonReservationDates = LessonReservationDates(alias, this)
    override fun `as`(alias: Table<*>): LessonReservationDates = LessonReservationDates(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): LessonReservationDates = LessonReservationDates(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): LessonReservationDates = LessonReservationDates(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): LessonReservationDates = LessonReservationDates(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): LessonReservationDates = LessonReservationDates(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): LessonReservationDates = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): LessonReservationDates = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): LessonReservationDates = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): LessonReservationDates = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): LessonReservationDates = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): LessonReservationDates = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): LessonReservationDates = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): LessonReservationDates = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): LessonReservationDates = where(DSL.notExists(select))
}
