/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables


import com.spotteacher.infra.db.tables.records.LessonScheduleEducationsRecord

import java.time.LocalDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class LessonScheduleEducations(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, LessonScheduleEducationsRecord>?,
    parentPath: InverseForeignKey<out Record, LessonScheduleEducationsRecord>?,
    aliased: Table<LessonScheduleEducationsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<LessonScheduleEducationsRecord>(
    alias,
    null,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>lesson_schedule_educations</code>
         */
        val LESSON_SCHEDULE_EDUCATIONS: LessonScheduleEducations = LessonScheduleEducations()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<LessonScheduleEducationsRecord> = LessonScheduleEducationsRecord::class.java

    /**
     * The column <code>lesson_schedule_educations.id</code>.
     */
    val ID: TableField<LessonScheduleEducationsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>lesson_schedule_educations.lesson_schedule_id</code>.
     */
    val LESSON_SCHEDULE_ID: TableField<LessonScheduleEducationsRecord, Long?> = createField(DSL.name("lesson_schedule_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>lesson_schedule_educations.education_id</code>.
     */
    val EDUCATION_ID: TableField<LessonScheduleEducationsRecord, Long?> = createField(DSL.name("education_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>lesson_schedule_educations.created_at</code>.
     */
    val CREATED_AT: TableField<LessonScheduleEducationsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>lesson_schedule_educations.updated_at</code>.
     */
    val UPDATED_AT: TableField<LessonScheduleEducationsRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<LessonScheduleEducationsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<LessonScheduleEducationsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<LessonScheduleEducationsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>lesson_schedule_educations</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>lesson_schedule_educations</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>lesson_schedule_educations</code> table reference
     */
    constructor(): this(DSL.name("lesson_schedule_educations"), null)
    override fun getIdentity(): Identity<LessonScheduleEducationsRecord, Long?> = super.getIdentity() as Identity<LessonScheduleEducationsRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<LessonScheduleEducationsRecord> = Internal.createUniqueKey(LessonScheduleEducations.LESSON_SCHEDULE_EDUCATIONS, DSL.name("KEY_lesson_schedule_educations_PRIMARY"), arrayOf(LessonScheduleEducations.LESSON_SCHEDULE_EDUCATIONS.ID), true)
    override fun `as`(alias: String): LessonScheduleEducations = LessonScheduleEducations(DSL.name(alias), this)
    override fun `as`(alias: Name): LessonScheduleEducations = LessonScheduleEducations(alias, this)
    override fun `as`(alias: Table<*>): LessonScheduleEducations = LessonScheduleEducations(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): LessonScheduleEducations = LessonScheduleEducations(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): LessonScheduleEducations = LessonScheduleEducations(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): LessonScheduleEducations = LessonScheduleEducations(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): LessonScheduleEducations = LessonScheduleEducations(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): LessonScheduleEducations = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): LessonScheduleEducations = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): LessonScheduleEducations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): LessonScheduleEducations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): LessonScheduleEducations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): LessonScheduleEducations = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): LessonScheduleEducations = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): LessonScheduleEducations = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): LessonScheduleEducations = where(DSL.notExists(select))
}
