/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables


import com.spotteacher.infra.db.enums.LessonReservationsLessonType
import com.spotteacher.infra.db.tables.records.LessonReservationsRecord

import java.time.LocalDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class LessonReservations(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, LessonReservationsRecord>?,
    parentPath: InverseForeignKey<out Record, LessonReservationsRecord>?,
    aliased: Table<LessonReservationsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<LessonReservationsRecord>(
    alias,
    null,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>lesson_reservations</code>
         */
        val LESSON_RESERVATIONS: LessonReservations = LessonReservations()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<LessonReservationsRecord> = LessonReservationsRecord::class.java

    /**
     * The column <code>lesson_reservations.id</code>.
     */
    val ID: TableField<LessonReservationsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>lesson_reservations.company_id</code>.
     */
    val COMPANY_ID: TableField<LessonReservationsRecord, Long?> = createField(DSL.name("company_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>lesson_reservations.school_id</code>.
     */
    val SCHOOL_ID: TableField<LessonReservationsRecord, Long?> = createField(DSL.name("school_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>lesson_reservations.teacher_id</code>.
     */
    val TEACHER_ID: TableField<LessonReservationsRecord, Long?> = createField(DSL.name("teacher_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>lesson_reservations.lesson_plan_id</code>.
     */
    val LESSON_PLAN_ID: TableField<LessonReservationsRecord, Long?> = createField(DSL.name("lesson_plan_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>lesson_reservations.title</code>.
     */
    val TITLE: TableField<LessonReservationsRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(500), this, "")

    /**
     * The column <code>lesson_reservations.description</code>.
     */
    val DESCRIPTION: TableField<LessonReservationsRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR(2000), this, "")

    /**
     * The column <code>lesson_reservations.location</code>.
     */
    val LOCATION: TableField<LessonReservationsRecord, String?> = createField(DSL.name("location"), SQLDataType.VARCHAR(500), this, "")

    /**
     * The column <code>lesson_reservations.lesson_type</code>.
     */
    val LESSON_TYPE: TableField<LessonReservationsRecord, LessonReservationsLessonType?> = createField(DSL.name("lesson_type"), SQLDataType.VARCHAR(18).asEnumDataType(LessonReservationsLessonType::class.java), this, "")

    /**
     * The column <code>lesson_reservations.created_at</code>.
     */
    val CREATED_AT: TableField<LessonReservationsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>lesson_reservations.updated_at</code>.
     */
    val UPDATED_AT: TableField<LessonReservationsRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<LessonReservationsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<LessonReservationsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<LessonReservationsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>lesson_reservations</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>lesson_reservations</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>lesson_reservations</code> table reference
     */
    constructor(): this(DSL.name("lesson_reservations"), null)
    override fun getIdentity(): Identity<LessonReservationsRecord, Long?> = super.getIdentity() as Identity<LessonReservationsRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<LessonReservationsRecord> = Internal.createUniqueKey(LessonReservations.LESSON_RESERVATIONS, DSL.name("KEY_lesson_reservations_PRIMARY"), arrayOf(LessonReservations.LESSON_RESERVATIONS.ID), true)
    override fun `as`(alias: String): LessonReservations = LessonReservations(DSL.name(alias), this)
    override fun `as`(alias: Name): LessonReservations = LessonReservations(alias, this)
    override fun `as`(alias: Table<*>): LessonReservations = LessonReservations(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): LessonReservations = LessonReservations(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): LessonReservations = LessonReservations(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): LessonReservations = LessonReservations(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): LessonReservations = LessonReservations(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): LessonReservations = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): LessonReservations = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): LessonReservations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): LessonReservations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): LessonReservations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): LessonReservations = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): LessonReservations = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): LessonReservations = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): LessonReservations = where(DSL.notExists(select))
}
