/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables


import com.spotteacher.infra.db.tables.records.LessonReservationGradesRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class LessonReservationGrades(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, LessonReservationGradesRecord>?,
    parentPath: InverseForeignKey<out Record, LessonReservationGradesRecord>?,
    aliased: Table<LessonReservationGradesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<LessonReservationGradesRecord>(
    alias,
    null,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>lesson_reservation_grades</code>
         */
        val LESSON_RESERVATION_GRADES: LessonReservationGrades = LessonReservationGrades()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<LessonReservationGradesRecord> = LessonReservationGradesRecord::class.java

    /**
     * The column <code>lesson_reservation_grades.lesson_reservation_id</code>.
     */
    val LESSON_RESERVATION_ID: TableField<LessonReservationGradesRecord, Long?> = createField(DSL.name("lesson_reservation_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>lesson_reservation_grades.grade_code</code>.
     */
    val GRADE_CODE: TableField<LessonReservationGradesRecord, String?> = createField(DSL.name("grade_code"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>lesson_reservation_grades.display_order</code>.
     */
    val DISPLAY_ORDER: TableField<LessonReservationGradesRecord, Int?> = createField(DSL.name("display_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "")

    private constructor(alias: Name, aliased: Table<LessonReservationGradesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<LessonReservationGradesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<LessonReservationGradesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>lesson_reservation_grades</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>lesson_reservation_grades</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>lesson_reservation_grades</code> table reference
     */
    constructor(): this(DSL.name("lesson_reservation_grades"), null)
    override fun getPrimaryKey(): UniqueKey<LessonReservationGradesRecord> = Internal.createUniqueKey(LessonReservationGrades.LESSON_RESERVATION_GRADES, DSL.name("KEY_lesson_reservation_grades_PRIMARY"), arrayOf(LessonReservationGrades.LESSON_RESERVATION_GRADES.LESSON_RESERVATION_ID, LessonReservationGrades.LESSON_RESERVATION_GRADES.GRADE_CODE), true)
    override fun `as`(alias: String): LessonReservationGrades = LessonReservationGrades(DSL.name(alias), this)
    override fun `as`(alias: Name): LessonReservationGrades = LessonReservationGrades(alias, this)
    override fun `as`(alias: Table<*>): LessonReservationGrades = LessonReservationGrades(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): LessonReservationGrades = LessonReservationGrades(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): LessonReservationGrades = LessonReservationGrades(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): LessonReservationGrades = LessonReservationGrades(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): LessonReservationGrades = LessonReservationGrades(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): LessonReservationGrades = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): LessonReservationGrades = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): LessonReservationGrades = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): LessonReservationGrades = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): LessonReservationGrades = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): LessonReservationGrades = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): LessonReservationGrades = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): LessonReservationGrades = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): LessonReservationGrades = where(DSL.notExists(select))
}
