/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables


import com.spotteacher.infra.db.tables.records.TeachersRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * Teacherロールを持つユーザーの情報
 */
@Suppress("warnings")
open class Teachers(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TeachersRecord>?,
    parentPath: InverseForeignKey<out Record, TeachersRecord>?,
    aliased: Table<TeachersRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TeachersRecord>(
    alias,
    null,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("Teacherロールを持つユーザーの情報"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>teachers</code>
         */
        val TEACHERS: Teachers = Teachers()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TeachersRecord> = TeachersRecord::class.java

    /**
     * The column <code>teachers.id</code>.
     */
    val ID: TableField<TeachersRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>teachers.user_id</code>.
     */
    val USER_ID: TableField<TeachersRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>teachers.school_id</code>.
     */
    val SCHOOL_ID: TableField<TeachersRecord, Long?> = createField(DSL.name("school_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>teachers.created_at</code>.
     */
    val CREATED_AT: TableField<TeachersRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>teachers.updated_at</code>.
     */
    val UPDATED_AT: TableField<TeachersRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<TeachersRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TeachersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TeachersRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>teachers</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>teachers</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>teachers</code> table reference
     */
    constructor(): this(DSL.name("teachers"), null)
    override fun getIdentity(): Identity<TeachersRecord, Long?> = super.getIdentity() as Identity<TeachersRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<TeachersRecord> = Internal.createUniqueKey(Teachers.TEACHERS, DSL.name("KEY_teachers_PRIMARY"), arrayOf(Teachers.TEACHERS.ID), true)
    override fun getUniqueKeys(): List<UniqueKey<TeachersRecord>> = listOf(
        Internal.createUniqueKey(Teachers.TEACHERS, DSL.name("KEY_teachers_user_id"), arrayOf(Teachers.TEACHERS.USER_ID), true)
    )
    override fun `as`(alias: String): Teachers = Teachers(DSL.name(alias), this)
    override fun `as`(alias: Name): Teachers = Teachers(alias, this)
    override fun `as`(alias: Table<*>): Teachers = Teachers(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Teachers = Teachers(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Teachers = Teachers(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Teachers = Teachers(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Teachers = Teachers(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Teachers = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Teachers = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Teachers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Teachers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Teachers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Teachers = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Teachers = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Teachers = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Teachers = where(DSL.notExists(select))
}
