/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables

import com.spotteacher.infra.db.enums.UploadFilesUploadStatus
import com.spotteacher.infra.db.tables.records.UploadFilesRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UploadFiles(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UploadFilesRecord>?,
    parentPath: InverseForeignKey<out Record, UploadFilesRecord>?,
    aliased: Table<UploadFilesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<UploadFilesRecord>(
    alias,
    null,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>UPLOAD_FILES</code>
         */
        val UPLOAD_FILES: UploadFiles = UploadFiles()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UploadFilesRecord> = UploadFilesRecord::class.java

    /**
     * The column <code>UPLOAD_FILES.id</code>.
     */
    val ID: TableField<UploadFilesRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>UPLOAD_FILES.file_key</code>.
     */
    val FILE_KEY: TableField<UploadFilesRecord, String?> = createField(DSL.name("file_key"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>UPLOAD_FILES.upload_status</code>.
     */
    val UPLOAD_STATUS: TableField<UploadFilesRecord, UploadFilesUploadStatus?> = createField(
        DSL.name("upload_status"),
        SQLDataType.VARCHAR(8).nullable(false).asEnumDataType(UploadFilesUploadStatus::class.java),
        this,
        ""
    )

    /**
     * The column <code>UPLOAD_FILES.created_at</code>.
     */
    val CREATED_AT: TableField<UploadFilesRecord, LocalDateTime?> = createField(
        DSL.name("created_at"),
        SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)),
        this,
        ""
    )

    /**
     * The column <code>UPLOAD_FILES.update_at</code>.
     */
    val UPDATE_AT: TableField<UploadFilesRecord, LocalDateTime?> = createField(
        DSL.name("update_at"),
        SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)),
        this,
        ""
    )

    private constructor(alias: Name, aliased: Table<UploadFilesRecord>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UploadFilesRecord>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UploadFilesRecord>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>UPLOAD_FILES</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>UPLOAD_FILES</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>UPLOAD_FILES</code> table reference
     */
    constructor() : this(DSL.name("UPLOAD_FILES"), null)
    override fun getIdentity(): Identity<UploadFilesRecord, Long?> = super.getIdentity() as Identity<UploadFilesRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<UploadFilesRecord> = Internal.createUniqueKey(UploadFiles.UPLOAD_FILES, DSL.name("KEY_UPLOAD_FILES_PRIMARY"), arrayOf(UploadFiles.UPLOAD_FILES.ID), true)
    override fun getUniqueKeys(): List<UniqueKey<UploadFilesRecord>> = listOf(
        Internal.createUniqueKey(UploadFiles.UPLOAD_FILES, DSL.name("KEY_UPLOAD_FILES_file_key"), arrayOf(UploadFiles.UPLOAD_FILES.FILE_KEY), true)
    )
    override fun `as`(alias: String): UploadFiles = UploadFiles(DSL.name(alias), this)
    override fun `as`(alias: Name): UploadFiles = UploadFiles(alias, this)
    override fun `as`(alias: Table<*>): UploadFiles = UploadFiles(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UploadFiles = UploadFiles(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UploadFiles = UploadFiles(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UploadFiles = UploadFiles(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): UploadFiles = UploadFiles(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): UploadFiles = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): UploadFiles = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): UploadFiles = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): UploadFiles = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): UploadFiles = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): UploadFiles = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): UploadFiles = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): UploadFiles = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): UploadFiles = where(DSL.notExists(select))
}
