/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables

import com.spotteacher.infra.db.enums.LessonPlansLessonType
import com.spotteacher.infra.db.tables.records.LessonPlansRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime
import kotlin.collections.Collection

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class LessonPlans(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, LessonPlansRecord>?,
    parentPath: InverseForeignKey<out Record, LessonPlansRecord>?,
    aliased: Table<LessonPlansRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<LessonPlansRecord>(
    alias,
    null,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>lesson_plans</code>
         */
        val LESSON_PLANS: LessonPlans = LessonPlans()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<LessonPlansRecord> = LessonPlansRecord::class.java

    /**
     * The column <code>lesson_plans.id</code>.
     */
    val ID: TableField<LessonPlansRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>lesson_plans.company_id</code>.
     */
    val COMPANY_ID: TableField<LessonPlansRecord, Long?> = createField(DSL.name("company_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>lesson_plans.title</code>.
     */
    val TITLE: TableField<LessonPlansRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(500).nullable(false), this, "")

    /**
     * The column <code>lesson_plans.description</code>.
     */
    val DESCRIPTION: TableField<LessonPlansRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR(2000), this, "")

    /**
     * The column <code>lesson_plans.location</code>.
     */
    val LOCATION: TableField<LessonPlansRecord, String?> = createField(DSL.name("location"), SQLDataType.VARCHAR(500), this, "")

    /**
     * The column <code>lesson_plans.lesson_type</code>.
     */
    val LESSON_TYPE: TableField<LessonPlansRecord, LessonPlansLessonType?> = createField(
        DSL.name("lesson_type"),
        SQLDataType.VARCHAR(18).nullable(false).asEnumDataType(LessonPlansLessonType::class.java),
        this,
        ""
    )

    /**
     * The column <code>lesson_plans.annual_max_executions</code>. 年間の最大実施回数
     */
    val ANNUAL_MAX_EXECUTIONS: TableField<LessonPlansRecord, Long?> = createField(DSL.name("annual_max_executions"), SQLDataType.BIGINT.nullable(false), this, "年間の最大実施回数")

    /**
     * The column <code>lesson_plans.created_at</code>.
     */
    val CREATED_AT: TableField<LessonPlansRecord, LocalDateTime?> = createField(
        DSL.name("created_at"),
        SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)),
        this,
        ""
    )

    /**
     * The column <code>lesson_plans.updated_at</code>.
     */
    val UPDATED_AT: TableField<LessonPlansRecord, LocalDateTime?> = createField(
        DSL.name("updated_at"),
        SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)),
        this,
        ""
    )

    private constructor(alias: Name, aliased: Table<LessonPlansRecord>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<LessonPlansRecord>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<LessonPlansRecord>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>lesson_plans</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>lesson_plans</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>lesson_plans</code> table reference
     */
    constructor() : this(DSL.name("lesson_plans"), null)
    override fun getIdentity(): Identity<LessonPlansRecord, Long?> = super.getIdentity() as Identity<LessonPlansRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<LessonPlansRecord> = Internal.createUniqueKey(LessonPlans.LESSON_PLANS, DSL.name("KEY_lesson_plans_PRIMARY"), arrayOf(LessonPlans.LESSON_PLANS.ID), true)
    override fun `as`(alias: String): LessonPlans = LessonPlans(DSL.name(alias), this)
    override fun `as`(alias: Name): LessonPlans = LessonPlans(alias, this)
    override fun `as`(alias: Table<*>): LessonPlans = LessonPlans(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): LessonPlans = LessonPlans(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): LessonPlans = LessonPlans(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): LessonPlans = LessonPlans(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): LessonPlans = LessonPlans(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): LessonPlans = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): LessonPlans = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): LessonPlans = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): LessonPlans = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): LessonPlans = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): LessonPlans = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): LessonPlans = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): LessonPlans = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): LessonPlans = where(DSL.notExists(select))
}
