/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables


import com.spotteacher.infra.db.tables.records.UserCredentialsRecord

import java.time.LocalDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UserCredentials(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UserCredentialsRecord>?,
    parentPath: InverseForeignKey<out Record, UserCredentialsRecord>?,
    aliased: Table<UserCredentialsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UserCredentialsRecord>(
    alias,
    null,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>user_credentials</code>
         */
        val USER_CREDENTIALS: UserCredentials = UserCredentials()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UserCredentialsRecord> = UserCredentialsRecord::class.java

    /**
     * The column <code>user_credentials.user_id</code>.
     */
    val USER_ID: TableField<UserCredentialsRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>user_credentials.password_hash</code>.
     */
    val PASSWORD_HASH: TableField<UserCredentialsRecord, String?> = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>user_credentials.last_password_change_at</code>.
     */
    val LAST_PASSWORD_CHANGE_AT: TableField<UserCredentialsRecord, LocalDateTime?> = createField(DSL.name("last_password_change_at"), SQLDataType.LOCALDATETIME(0), this, "")

    /**
     * The column <code>user_credentials.failed_login_attempts</code>.
     */
    val FAILED_LOGIN_ATTEMPTS: TableField<UserCredentialsRecord, Int?> = createField(DSL.name("failed_login_attempts"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>user_credentials.locked_until</code>.
     */
    val LOCKED_UNTIL: TableField<UserCredentialsRecord, LocalDateTime?> = createField(DSL.name("locked_until"), SQLDataType.LOCALDATETIME(0), this, "")

    /**
     * The column <code>user_credentials.created_at</code>.
     */
    val CREATED_AT: TableField<UserCredentialsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>user_credentials.updated_at</code>.
     */
    val UPDATED_AT: TableField<UserCredentialsRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<UserCredentialsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UserCredentialsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UserCredentialsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>user_credentials</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>user_credentials</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>user_credentials</code> table reference
     */
    constructor(): this(DSL.name("user_credentials"), null)
    override fun getPrimaryKey(): UniqueKey<UserCredentialsRecord> = Internal.createUniqueKey(UserCredentials.USER_CREDENTIALS, DSL.name("KEY_user_credentials_PRIMARY"), arrayOf(UserCredentials.USER_CREDENTIALS.USER_ID), true)
    override fun `as`(alias: String): UserCredentials = UserCredentials(DSL.name(alias), this)
    override fun `as`(alias: Name): UserCredentials = UserCredentials(alias, this)
    override fun `as`(alias: Table<*>): UserCredentials = UserCredentials(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserCredentials = UserCredentials(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserCredentials = UserCredentials(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserCredentials = UserCredentials(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): UserCredentials = UserCredentials(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): UserCredentials = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): UserCredentials = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): UserCredentials = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): UserCredentials = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): UserCredentials = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): UserCredentials = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): UserCredentials = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): UserCredentials = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): UserCredentials = where(DSL.notExists(select))
}
