@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables.references


import com.spotteacher.infra.db.tables.Companies
import com.spotteacher.infra.db.tables.Products



/**
 * The table <code>companies</code>.
 */
val COMPANIES: Companies = Companies.COMPANIES

/**
 * The table <code>products</code>.
 */
val PRODUCTS: Products = Products.PRODUCTS
