@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables.references


import com.spotteacher.infra.db.tables.Products



/**
 * The table <code>products</code>.
 */
val PRODUCTS: Products = Products.PRODUCTS
