CREATE TABLE IF NOT EXISTS upload_files
(
    id            BIGINT AUTO_INCREMENT PRIMARY KEY,
    file_key      VARCHAR(255)                        NOT NULL UNIQUE,
    upload_status ENUM ('PENDING', 'UPLOADED')        NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IDX_UK_UPLOAD_FILES_FILE_KEY ON UPLOAD_FILES (file_key);
