/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.enums


import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
enum class LessonReservationsLessonType(@get:JvmName("literal") public val literal: String) : EnumType {
    ONLINE("ONLINE"),
    OFFLINE("OFFLINE"),
    ONLINE_AND_OFFLINE("ONLINE_AND_OFFLINE");
    override fun getCatalog(): Catalog? = null
    override fun getSchema(): Schema? = null
    override fun getName(): String? = null
    override fun getLiteral(): String = literal
}
