/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.enums

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
enum class SchoolsSchoolCategory(@get:JvmName("literal") public val literal: String) : EnumType {
    ELEMENTARY("ELEMENTARY"),
    JUNIOR_HIGH("JUNIOR_HIGH"),
    HIGH("HIGH");
    override fun getCatalog(): Catalog? = null
    override fun getSchema(): Schema? = null
    override fun getName(): String? = null
    override fun getLiteral(): String = literal
}
