/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables.records


import com.spotteacher.infra.db.tables.LessonPlanSubjects

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class LessonPlanSubjectsRecord private constructor() : UpdatableRecordImpl<LessonPlanSubjectsRecord>(LessonPlanSubjects.LESSON_PLAN_SUBJECTS) {

    open var lessonPlanId: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    open var subjectCode: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Long?, String?> = super.key() as Record2<Long?, String?>

    /**
     * Create a detached, initialised LessonPlanSubjectsRecord
     */
    constructor(lessonPlanId: Long, subjectCode: String): this() {
        this.lessonPlanId = lessonPlanId
        this.subjectCode = subjectCode
        resetTouchedOnNotNull()
    }
}
