/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables.records


import com.spotteacher.infra.db.tables.LessonPlansEducations

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class LessonPlansEducationsRecord private constructor() : UpdatableRecordImpl<LessonPlansEducationsRecord>(LessonPlansEducations.LESSON_PLANS_EDUCATIONS) {

    open var lessonPlanId: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    open var educationId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Long?, Long?> = super.key() as Record2<Long?, Long?>

    /**
     * Create a detached, initialised LessonPlansEducationsRecord
     */
    constructor(lessonPlanId: Long, educationId: Long): this() {
        this.lessonPlanId = lessonPlanId
        this.educationId = educationId
        resetTouchedOnNotNull()
    }
}
