/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables.records


import com.spotteacher.infra.db.tables.LessonPlanGrades

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class LessonPlanGradesRecord private constructor() : UpdatableRecordImpl<LessonPlanGradesRecord>(LessonPlanGrades.LESSON_PLAN_GRADES) {

    open var lessonPlanId: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    open var gradeCode: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Long?, String?> = super.key() as Record2<Long?, String?>

    /**
     * Create a detached, initialised LessonPlanGradesRecord
     */
    constructor(lessonPlanId: Long, gradeCode: String): this() {
        this.lessonPlanId = lessonPlanId
        this.gradeCode = gradeCode
        resetTouchedOnNotNull()
    }
}
