/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables.records


import com.spotteacher.infra.db.tables.Products

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.types.UInteger
import org.jooq.types.ULong


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ProductsRecord private constructor() : UpdatableRecordImpl<ProductsRecord>(Products.PRODUCTS) {

    open var id: ULong?
        set(value): Unit = set(0, value)
        get(): ULong? = get(0) as ULong?

    open var name: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var price: UInteger
        set(value): Unit = set(2, value)
        get(): UInteger = get(2) as UInteger

    open var description: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<ULong?> = super.key() as Record1<ULong?>

    /**
     * Create a detached, initialised ProductsRecord
     */
    constructor(id: ULong? = null, name: String, price: UInteger, description: String? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null): this() {
        this.id = id
        this.name = name
        this.price = price
        this.description = description
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
