/*
 * This file is generated by jOOQ.
 */
package com.spotteacher.infra.db.tables.records


import com.spotteacher.infra.db.tables.RefreshTokens

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class RefreshTokensRecord private constructor() : UpdatableRecordImpl<RefreshTokensRecord>(RefreshTokens.REFRESH_TOKENS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var userId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open var token: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var expiresAt: LocalDateTime
        set(value): Unit = set(3, value)
        get(): LocalDateTime = get(3) as LocalDateTime

    open var createdAt: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised RefreshTokensRecord
     */
    constructor(id: Long? = null, userId: Long, token: String, expiresAt: LocalDateTime, createdAt: LocalDateTime? = null): this() {
        this.id = id
        this.userId = userId
        this.token = token
        this.expiresAt = expiresAt
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }
}
